"""initial migration

Revision ID: 245493edf6a3
Revises: None
Create Date: 2014-10-12 16:31:09.480666

"""

# revision identifiers, used by Alembic.
revision = '245493edf6a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_table('units')
    ### end Alembic commands ###
